---

- hosts: "all"
  become: True
  become_user: root
  vars_files:
    - 'variables.yml'

  tasks:
  - name: "Install libselinux-python on all servers"
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - libselinux-python
  
  - name: "Install EPEL Release"
    package:
      name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      
  - name: "Removing mariadb-libs"
    yum:
      name: 'mariadb-libs'
      state: absent

  - name: "Setting Selinux To Permissive"
    selinux:
      policy: targeted
      state: permissive

  - name: "Upgrading All Packages"
    yum:
      name: '*'
      state: latest

  - name: Installing Some Basic Packages
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - wget
      - nano
      - pigz
      - socat
      - python2
      - python3
      - python2-pip
      - python3-pip

  - name: "Installing PyMySQL Module"
    pip:
      name: PyMySQL

- hosts: "xpand"
  become: True
  become_user: root
  vars_files:
    - 'variables.yml'
    - '/tmp/file_variables.yml'

  tasks:

  - name: "Download MariaDB ES Repo setup"
    get_url:
      url: "{{ mariadbrepo_url }}"
      dest: /tmp/mariadb_es_repo_setup
      mode: '0777'

  - name: "Set ES repo setup to executable"
    file:
      path: /tmp/mariadb_es_repo_setup
      owner: root
      group: root
      mode: 0755

  - name: "Install MariaDB ES Repo"
    shell: /tmp/mariadb_es_repo_setup --token={{ customer_token }} --apply --mariadb-server-version="10.5"
  - name: "Reloading Systemd"
    command: systemctl daemon-reload
  
  - name: "Install MariaDB Server"
    yum:
      name: mariadb-server
  - name: "Install MariaDB Xpand Plugin"
    yum:
      name: MariaDB-xpand-engine
      
  - name: Insert a line at the end of a file.
    blockinfile:
     dest: /etc/my.cnf.d/xpand.cnf
     block: |
      plugin-maturity=beta
      xpand_hosts=10.0.2.11
      xpand_port=4799
      xpand_username=root
      
  - name: "Creating MySQL Log Directory"
    file:
      path: /var/log/mysql
      state: directory
      mode: 0755
      owner: mysql
      group: mysql
      
  - name: "Creating mariadb Log Directory"
    file:
      path: /var/log/mariadb
      state: directory
      mode: 0755
      owner: mysql
      group: mysql

  - name: "Creating/Updating server.cnf"
    template:
      src: templates/general_xpand.j2
      dest: /etc/my.cnf.d/server.cnf

  - name: "Installing/Updating timeouts.conf Template"
    template:
      src: templates/timeouts.j2
      dest: /etc/systemd/system/mariadb.service.d/timeouts.conf

  - name: "Setting Soft Open File Limits"
    pam_limits:
      domain: '*'
      limit_type: soft
      limit_item: nofile
      value: 65535

  - name: "Setting Hard Open File Limits"
    pam_limits:
      domain: '*'
      limit_type: hard
      limit_item: nofile
      value: 65535

  - name: "Adjusting OS Swappiness"
    sysctl:
      name: vm.swappiness
      value: 1
      state: present
      
- hosts: xpand
  become: True
  become_user: root
  vars_files:
    - '/tmp/file_variables.yml'

  tasks:

  - name: "Installing bzip2"
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - bzip2
      - http://mirror.centos.org/centos/7/os/x86_64/Packages/libdwarf-tools-20130207-4.el7.x86_64.rpm

  - name: "Downloading Xpand"
    get_url:
      url: "{{ xpand_url }}"
      dest: /tmp/xpand.tar.bz2
      mode: '0777'

    
  - name: Uncompressing Xpand binaries
    command: tar xvf /tmp/xpand.tar.bz2 -C /tmp
    
  - name: "Startng Xpand"
    command: chdir=/tmp/{{ xpand_dir }} ./clxnode_install.py --mysql-port=4799 --yes

  - name: "Granting remote access"
    command: mysql -uroot -P4799 -e "grant all on *.* to 'root'@'%';"
